# -*- coding: utf-8 -*-
"""
AI_SYSTEM/CORE_UTILS/emotion_reactor.py

EmotionReactor: Dynamic tone and empathy modulation layer for RoboRana.

Purpose:
- Adjust response tone based on detected emotion and conversational context.
- Add small adaptive reactions (empathy, humor, reassurance) based on emotion.
- Integrates with ChatBrain + IntentEmotionEngine + SharedLogic personality system.

Drop this into: AI_SYSTEM/CORE_UTILS/

Author: Generated for Sandeep Rana / RoboRana
"""

import random
import re
from datetime import datetime
from typing import Optional, Dict


class EmotionReactor:
    """
    EmotionReactor enhances the emotional intelligence of RoboRana responses.
    It post-processes text generated by agents before final delivery.
    """

    def __init__(self, shared_logic: Optional[object] = None):
        self.shared_logic = shared_logic
        self.default_tone = "neutral"

        # Predefined emotional reactions
        self.reactions = {
            "positive": [
                "😊 That’s great to hear!",
                "👍 Love the energy!",
                "💪 Perfect — let’s keep that momentum going!"
            ],
            "negative": [
                "😕 I see what you mean. Let’s fix that.",
                "😔 Noted — we’ll get this right.",
                "🙁 Don’t worry, I’ll handle it step-by-step."
            ],
            "angry": [
                "😬 I get your frustration, let’s calm things down and fix it.",
                "😤 That sounds annoying — I’ll resolve it quickly.",
                "⚡ I feel your anger, let’s tackle this with focus."
            ],
            "confused": [
                "🤔 Let me clarify that.",
                "😅 No worries, I’ll explain it simply.",
                "🧩 Seems unclear — let’s break it down together."
            ],
            "neutral": [
                "👌 Got it.",
                "Alright.",
                "Understood."
            ],
            "frustrated": [
                "😞 Let’s try a different approach.",
                "I get it, this can be tricky — we’ll sort it out.",
                "Let’s go step by step until it’s right."
            ]
        }

        # Tone calibration styles
        self.tone_styles = {
            "formal": {
                "prefix": "Certainly.",
                "suffix": "Please allow me to elaborate further if required.",
                "emoji": "🤖"
            },
            "casual": {
                "prefix": random.choice(["Cool,", "Bro,", "Okay,", "Hey,"]),
                "suffix": random.choice(["😉", "😎", "👍"]),
                "emoji": random.choice(["🙂", "😄"])
            },
            "friendly": {
                "prefix": "Hey there!",
                "suffix": "😊",
                "emoji": "✨"
            },
            "neutral": {
                "prefix": "",
                "suffix": "",
                "emoji": ""
            }
        }

    # -----------------------
    # Core Functions
    # -----------------------
    def react(self, text: str, emotion: str = "neutral", tone: str = "neutral", agent_type: Optional[str] = None) -> str:
        """
        Adjusts response tone and empathy based on emotion & tone.
        Optionally varies by agent personality.
        """

        if self._should_skip_rewrite(text):
            return text if isinstance(text, str) else str(text)

        text = "" if text is None else str(text)
        emotion = emotion or "neutral"
        tone = tone or self.default_tone

        # Step 1: Get emotional reaction
        reaction = random.choice(self.reactions.get(emotion, [""]))
        prefix, suffix, emoji = self._get_tone_modifiers(tone)

        # Step 2: Apply shared personality logic (if provided)
        if self.shared_logic and hasattr(self.shared_logic, "adjust_personality_tone"):
            text = self.shared_logic.adjust_personality_tone(text, agent_type or "general")

        # Step 3: Combine with emotional modulation
        final_text = f"{prefix} {reaction} {text.strip()} {suffix} {emoji}".strip()
        return " ".join(final_text.split())

    def _should_skip_rewrite(self, text: str) -> bool:
        """
        Detect responses where emotional rewriting should be skipped.
        """
        if not isinstance(text, str):
            return True

        t = text.strip()
        if not t:
            return True

        protected_markers = [
            "###", "```", "|", "•", "1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣",
            "Spend:", "Revenue:", "ROAS", "CTR", "CPC",
            "Ads spend was", "ROAS was", "Please tell me exactly",
            "This looks like", "This seems related"
        ]
        if any(marker in t for marker in protected_markers):
            return True

        if "\n" in t and any(line.strip().startswith(("-", "•", "#")) for line in t.splitlines()):
        if self._is_structured_or_metric_response(text):
            return text.strip()

        final_text = f"{prefix} {reaction} {text.strip()} {suffix} {emoji}".strip()
        return " ".join(final_text.split())

    def _is_structured_or_metric_response(self, text: str) -> bool:
        """
        Detect structured/metric-heavy responses where decoration can corrupt intent.
        """
        t = (text or "").strip()
        if not t:
            return True

        markdown_tokens = ("```", "|", "#", "##", "###", "- ", "* ", "1.", "2.", "3.")
        if any(token in t for token in markdown_tokens):
            return True

        if re.search(r"\d", t):
            return True

        if any(sym in t for sym in ("₹", "$", "%", "->", "=>", "::", "{", "}", "[", "]")):
            return True

        return False

    def _get_tone_modifiers(self, tone: str) -> tuple:
        """Return (prefix, suffix, emoji) modifiers based on tone style."""
        style = self.tone_styles.get(tone, self.tone_styles["neutral"])
        return style["prefix"], style["suffix"], style["emoji"]

    # -----------------------
    # Smart Response Helpers
    # -----------------------
    def quick_empathy(self, emotion: str) -> str:
        """Return a quick empathy line (without main text)."""
        reaction = random.choice(self.reactions.get(emotion, [""]))
        return reaction

    def inject_reactor_signature(self, text: str) -> str:
        """Add subtle signature (timestamp for debugging or analytics)."""
        ts = datetime.utcnow().strftime("%H:%M:%S")
        return f"{text}  · [EmotionReactor {ts}]"


# -----------------------------
# Integration helper
# -----------------------------
def attach_emotion_reactor(agent, reactor: Optional[EmotionReactor] = None):
    """Attach EmotionReactor to an agent dynamically."""
    if reactor is None:
        reactor = EmotionReactor()
    setattr(agent, "emotion_reactor", reactor)

    def react_response(text, emotion="neutral", tone="neutral", agent_type=None):
        return reactor.react(text, emotion, tone, agent_type)

    setattr(agent, "react_response", react_response)
    return reactor


# -----------------------------
# Quick Self-Test
# -----------------------------
if __name__ == "__main__":
    reactor = EmotionReactor()
    print(reactor.react("Sales have dropped this week", emotion="negative", tone="formal", agent_type="sales"))
    print(reactor.react("Okay bro, done!", emotion="positive", tone="casual", agent_type="manager"))
    print(reactor.react("I am confused about Ajio data", emotion="confused", tone="friendly", agent_type="inventory"))
